### ISSUE TITLE
Anlegen von mehreren "einfachen Navigationen" nicht möglich

### ISSUE THREAD

**Issue by alexwenz** [ichbeigit/GUINavigation#1]
Habe eine einfache Navigation "footer" angelegt und möchte eine weitere "meta" hinzufügen. Bei Klick auf das "+" wird die vorhandene footer bearbeitet und überschrieben.

Redaxo 5.6.4
PHP 7.1.3
yform 2.3

**Comment by ichbeigit** [comment]
Hallo Alex,
bei git ist GUINavigation leider nicht auf dem neusten Stand. Hier gibt es nur die Version 1.0.1, von der ich weiß das sie das Problem hat. BeiM REDAXO-Installer gibt es auch die Versionen 1.0.2 und 1.0.3, die das Problem nicht haben. 
Falls bei dir das Problem auch bei Version 1.0.3. weiter besteht, dann melde dich doch bitte nochmal.
Grüße, ibg
P.S. Werde bald mal git updaten.

**Comment by alexwenz** [comment]
Sorry. Das wichtigste habe ich nicht reingeschrieben. Die Version war bzw. ist 1.0.3

**Comment by ichbeigit** [comment]
Der Fehler wurde mit der v. 1.0.3 leider nur beim Update beseitigt, war aber bei einer Neuinstallation noch da. Jetzt gibt es eine Version 1.0.4 bei Redaxo.

**Comment by alexwenz** [comment]
Super. Hat funktioniert. Vielen Dank für den schnellen Fix!!!
